steps:
- name: "gcr.io/cloud-builders/gcloud"
  args:
    - kms
    - decrypt
    - "--location=asia-northeast1"
    - "--keyring=mediadev"
    - "--key=config"
    - "--plaintext-file=config/dev-secret.json"
    - "--ciphertext-file=config/dev-secret.json.enc"
  id: Decrypt
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"